spring:
  cloud:
    kubernetes:
      enabled: true
      config:
        enabled: true
      reload:
        enabled: true
  datasource:
    url: jdbc:p6spy:postgresql://{{ lookup('env', 'DATABASE_URL') }}:5432/qrcheck
    username: qrcheck
    password: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      37323734333130343939626430663364366361396434616339343033616335613836623936363861
      3531666533616339616566613965613163346561376465620a353530376162383562646538323037
      38636233643839383364393038336434396335613731336263303434623831653535393038666163
      6537336535313266620a643532626361363531663535636537343464666639613032313665613163
      3365
  security:
    api_key:
      token:
        incoming:
          - !vault |
            $ANSIBLE_VAULT;1.1;AES256
            36333533633531343461333161643966393162326437383465346466303438346538626561366639
            6237613464373438326536626537363338323464363964320a356332326164323664346135643639
            37346437643138343731363838393530346231306235643164326237363735323134383166356232
            3562353265313931360a366265626661366135313637313962376530653339323133373964356232
            39356465336363306136373737333538663964656131613637643632366239633965633462623262
            6634643131333939336362393165663763363333663637343535
        outgoing: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          31663832396666366362386562663730376231353231363636663137633037363235383038333766
          3565333039656562383536346131326230346465616361300a383837623562633735313735646464
          65363033633361613030663038323663643538386565643834653330316239393964323231336235
          6362336161356436630a323733623835623334333366643563303363653364643838393536323232
          38316561323032303264323930373936356562366234326464666135343735373031353062323235
          3838643665376561353439363733383437316364636331343334

springdoc:
  api_docs:
    enabled: true